apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/data.framework.kubedoop.dev_dataassets.yaml
  - bases/data.framework.kubedoop.dev_dataoperations.yaml
  - rbac.yaml
