// Code generated by operator-go inputgen; DO NOT EDIT.
// Package registration connects the generated API to the framework operator.
package registration

import (
	generated "github.com/zncdatadev/operator-go/examples/trino-operator/api/v1alpha1"
	product0 "github.com/zncdatadev/operator-go/examples/trino-operator/internal/product"
	framework "github.com/zncdatadev/operator-go/pkg/framework"
	input "github.com/zncdatadev/operator-go/pkg/framework/input"
	operator "github.com/zncdatadev/operator-go/pkg/framework/operator"
	ctrl "sigs.k8s.io/controller-runtime"
)

const InputContractVersion = 1

// Options supplies product facts and platform settings without pipeline bindings.
type Options[F any] = operator.Options[product0.TrinoConfig, product0.TrinoClusterConfig, F]

// Register fixes the generated API's C/S types; F is inferred from the definition
// and deployment options. It registers the controller but does not start manager.
func Register[F any](manager ctrl.Manager,
	definition framework.ProductDefinition[product0.TrinoConfig, product0.TrinoClusterConfig, F], options Options[F],
) error {
	if err := input.CheckVersion(InputContractVersion); err != nil {
		return err
	}
	return operator.Register(manager, definition, options, generated.Binding())
}
