// Code generated by operator-go inputgen; DO NOT EDIT.
package testinput

import (
	"encoding/json"
	"fmt"
	"sort"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	"github.com/zncdatadev/operator-go/pkg/framework"
	"github.com/zncdatadev/operator-go/pkg/framework/input"
)

const InputContractVersion = 1

var GroupVersion = schema.GroupVersion{Group: "pipeline.tests.kubedoop.dev", Version: "v1alpha1"}
var SchemeBuilder = runtime.NewSchemeBuilder(func(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(GroupVersion, &TrinoCluster{}, &TrinoClusterList{})
	metav1.AddToGroupVersion(scheme, GroupVersion)
	return nil
})
var AddToScheme = SchemeBuilder.AddToScheme

type TrinoCluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SpecInput                 `json:"spec"`
	Status            framework.ReconcileStatus `json:"status,omitempty"`
}

type TrinoClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrinoCluster `json:"items"`
}

type SpecInput struct {
	Image         *input.ImageInput   `json:"image,omitempty"`
	ClusterConfig *ClusterConfigInput `json:"clusterConfig,omitempty"`
	Coordinators  *RoleInput          `json:"coordinators,omitempty"`
	Workers       *RoleInput          `json:"workers,omitempty"`
}

type RoleInput struct {
	RoleConfig      *input.RoleConfigInput         `json:"roleConfig,omitempty"`
	Replicas        *int32                         `json:"replicas,omitempty"`
	Config          *ConfigInput                   `json:"config,omitempty"`
	ConfigOverrides *map[string]input.FileOverride `json:"configOverrides,omitempty"`
	EnvOverrides    *map[string]string             `json:"envOverrides,omitempty"`
	CLIOverrides    *[]string                      `json:"cliOverrides,omitempty"`
	PodOverrides    json.RawMessage                `json:"podOverrides,omitempty"`
	RoleGroups      map[string]RoleGroupInput      `json:"roleGroups,omitempty"`
}

type RoleGroupInput struct {
	Replicas        *int32                         `json:"replicas,omitempty"`
	Config          *ConfigInput                   `json:"config,omitempty"`
	ConfigOverrides *map[string]input.FileOverride `json:"configOverrides,omitempty"`
	EnvOverrides    *map[string]string             `json:"envOverrides,omitempty"`
	CLIOverrides    *[]string                      `json:"cliOverrides,omitempty"`
	PodOverrides    json.RawMessage                `json:"podOverrides,omitempty"`
}

type ConfigInputResourcesCPU struct {
	Min *resource.Quantity `json:"min,omitempty"`
	Max *resource.Quantity `json:"max,omitempty"`
}

type ConfigInputResourcesMemory struct {
	Limit *resource.Quantity `json:"limit,omitempty"`
}

type ConfigInputResourcesStorage struct {
	Type             *string            `json:"type,omitempty"`
	StorageClassName *string            `json:"storageClassName,omitempty"`
	Capacity         *resource.Quantity `json:"capacity,omitempty"`
}

type ConfigInputResources struct {
	CPU     *ConfigInputResourcesCPU     `json:"cpu,omitempty"`
	Memory  *ConfigInputResourcesMemory  `json:"memory,omitempty"`
	Storage *ConfigInputResourcesStorage `json:"storage,omitempty"`
}

type ConfigInputLoggingContainersValueConsole struct {
	Level *string `json:"level,omitempty"`
}

type ConfigInputLoggingContainersValueFile struct {
	Level *string `json:"level,omitempty"`
}

type ConfigInputLoggingContainersValueLoggersValue struct {
	Level *string `json:"level,omitempty"`
}

type ConfigInputLoggingContainersValue struct {
	Console *ConfigInputLoggingContainersValueConsole                 `json:"console,omitempty"`
	File    *ConfigInputLoggingContainersValueFile                    `json:"file,omitempty"`
	Loggers *map[string]ConfigInputLoggingContainersValueLoggersValue `json:"loggers,omitempty"`
}

type ConfigInputLogging struct {
	EnableVectorAgent *bool                                         `json:"enableVectorAgent,omitempty"`
	Containers        *map[string]ConfigInputLoggingContainersValue `json:"containers,omitempty"`
}

type ConfigInput struct {
	Resources               *ConfigInputResources `json:"resources,omitempty"`
	Logging                 *ConfigInputLogging   `json:"logging,omitempty"`
	Affinity                *corev1.Affinity      `json:"affinity,omitempty"`
	GracefulShutdownTimeout *metav1.Duration      `json:"gracefulShutdownTimeout,omitempty"`
	HTTPPort                *int32                `json:"httpPort,omitempty"`
	CatalogConfigMapName    *string               `json:"catalogConfigMapName,omitempty"`
}

type ClusterConfigInputAuthenticationItemOIDC struct {
	ClientCredentialsSecret *string   `json:"clientCredentialsSecret,omitempty"`
	ExtraScopes             *[]string `json:"extraScopes,omitempty"`
}

type ClusterConfigInputAuthenticationItem struct {
	AuthenticationClass *string                                   `json:"authenticationClass,omitempty"`
	OIDC                *ClusterConfigInputAuthenticationItemOIDC `json:"oidc,omitempty"`
}

type ClusterConfigInput struct {
	Stopped              *bool                                   `json:"stopped,omitempty"`
	ReconciliationPaused *bool                                   `json:"reconciliationPaused,omitempty"`
	VectorAgentConfigMap *string                                 `json:"vectorAgentConfigMap,omitempty"`
	Authentication       *[]ClusterConfigInputAuthenticationItem `json:"authentication,omitempty"`
	NodeEnvironment      *string                                 `json:"nodeEnvironment,omitempty"`
}

func (in *TrinoCluster) DeepCopyInto(out *TrinoCluster) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = input.Clone(in.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *TrinoCluster) DeepCopy() *TrinoCluster {
	if in == nil {
		return nil
	}
	out := new(TrinoCluster)
	in.DeepCopyInto(out)
	return out
}
func (in *TrinoCluster) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	return in.DeepCopy()
}
func (in *TrinoClusterList) DeepCopyInto(out *TrinoClusterList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TrinoCluster, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *TrinoClusterList) DeepCopy() *TrinoClusterList {
	if in == nil {
		return nil
	}
	out := new(TrinoClusterList)
	in.DeepCopyInto(out)
	return out
}
func (in *TrinoClusterList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	return in.DeepCopy()
}

// Decode is the strict local JSON entry point. A typed API-server GET is the
// other supported input path; ordinary json.Unmarshal alone loses null values.
func Decode(data []byte) (*TrinoCluster, error) {
	var out TrinoCluster
	if err := input.DecodeJSON(data, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Operation reads only fixed controls, before projection or product validation.
// It neither marshals product fields nor changes the declared replica inventory.
func Operation(in *TrinoCluster) framework.ClusterOperation {
	var out framework.ClusterOperation
	if in == nil || in.Spec.ClusterConfig == nil {
		return out
	}
	controls := in.Spec.ClusterConfig
	if controls.Stopped != nil {
		out.Stopped = *controls.Stopped
	}
	if controls.ReconciliationPaused != nil {
		out.ReconciliationPaused = *controls.ReconciliationPaused
	}
	return out
}

// Project preserves raw layer presence and the complete declared role inventory.
// It neither folds replicas/config nor carries facts or runtime control state.
func Project(in *TrinoCluster) (input.Projection, error) {
	var out input.Projection
	if in == nil {
		return out, fmt.Errorf("input CR is required")
	}
	out.Cluster = framework.ClusterIdentity{
		Name: in.Name, Namespace: in.Namespace, Labels: input.Clone(in.Labels),
	}
	image, err := input.ConfigJSON(in.Spec.Image)
	if err != nil {
		return out, fmt.Errorf("image: %w", err)
	}
	out.Image = image
	clusterConfig, err := input.ClusterConfigJSON(in.Spec.ClusterConfig)
	if err != nil {
		return out, fmt.Errorf("clusterConfig: %w", err)
	}
	out.ClusterConfig = clusterConfig
	roles := []struct {
		name  string
		value *RoleInput
	}{
		{"coordinators", in.Spec.Coordinators},
		{"workers", in.Spec.Workers},
	}
	for _, entry := range roles {
		if entry.value == nil {
			continue
		}
		role := entry.value
		management, err := input.ConfigJSON(role.RoleConfig)
		if err != nil {
			return out, fmt.Errorf("%s.roleConfig: %w", entry.name, err)
		}
		config, err := input.ConfigJSON(role.Config)
		if err != nil {
			return out, fmt.Errorf("%s.config: %w", entry.name, err)
		}
		projected := input.Role{Name: entry.name, Replicas: input.Clone(role.Replicas),
			Config: config, RoleConfig: management,
			Overrides: inputOverrides(role.ConfigOverrides, role.EnvOverrides, role.CLIOverrides, role.PodOverrides),
		}
		groups := make([]string, 0, len(role.RoleGroups))
		for name := range role.RoleGroups {
			groups = append(groups, name)
		}
		sort.Strings(groups)
		for _, name := range groups {
			group := role.RoleGroups[name]
			config, err := input.ConfigJSON(group.Config)
			if err != nil {
				return out, fmt.Errorf("%s/%s.config: %w", entry.name, name, err)
			}
			projected.Groups = append(projected.Groups, input.Group{
				Name: name, Replicas: input.Clone(group.Replicas), Config: config,
				Overrides: inputOverrides(
					group.ConfigOverrides, group.EnvOverrides, group.CLIOverrides, group.PodOverrides),
			})
		}
		out.Roles = append(out.Roles, projected)
	}
	return out, nil
}

// Binding is the versioned generated-code bridge, not a product controller.
func Binding() input.Binding[*TrinoCluster] {
	return input.Binding[*TrinoCluster]{
		Version:     InputContractVersion,
		Roles:       []string{"coordinators", "workers"},
		AddToScheme: AddToScheme,
		NewObject:   func() *TrinoCluster { return &TrinoCluster{} },
		Operation:   Operation, Project: Project,
		Status: func(in *TrinoCluster) *framework.ReconcileStatus { return &in.Status },
	}
}

func inputOverrides(
	files *map[string]input.FileOverride, env *map[string]string, cli *[]string, pod json.RawMessage,
) *input.Overrides {
	if files == nil && env == nil && cli == nil && len(pod) == 0 {
		return nil
	}
	out := &input.Overrides{
		CLIOverrides: input.Clone(cli), PodOverrides: input.Clone(pod),
	}
	if files != nil {
		out.ConfigOverrides = input.Clone(*files)
	}
	if env != nil {
		out.EnvOverrides = input.Clone(*env)
	}
	return out
}
