//go:build !ignore_autogenerated

/*
Copyright 2024 zncdatadev.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonsv1alpha1 "github.com/zncdatadev/operator-go/pkg/apis/commons/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationClass) DeepCopyInto(out *AuthenticationClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationClass.
func (in *AuthenticationClass) DeepCopy() *AuthenticationClass {
	if in == nil {
		return nil
	}
	out := new(AuthenticationClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthenticationClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationClassList) DeepCopyInto(out *AuthenticationClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthenticationClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationClassList.
func (in *AuthenticationClassList) DeepCopy() *AuthenticationClassList {
	if in == nil {
		return nil
	}
	out := new(AuthenticationClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthenticationClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationClassSpec) DeepCopyInto(out *AuthenticationClassSpec) {
	*out = *in
	if in.AuthenticationProvider != nil {
		in, out := &in.AuthenticationProvider, &out.AuthenticationProvider
		*out = new(AuthenticationProvider)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationClassSpec.
func (in *AuthenticationClassSpec) DeepCopy() *AuthenticationClassSpec {
	if in == nil {
		return nil
	}
	out := new(AuthenticationClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationClassStatus) DeepCopyInto(out *AuthenticationClassStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationClassStatus.
func (in *AuthenticationClassStatus) DeepCopy() *AuthenticationClassStatus {
	if in == nil {
		return nil
	}
	out := new(AuthenticationClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticationProvider) DeepCopyInto(out *AuthenticationProvider) {
	*out = *in
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSPrivider)
		**out = **in
	}
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.LDAP != nil {
		in, out := &in.LDAP, &out.LDAP
		*out = new(LDAPProvider)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticationProvider.
func (in *AuthenticationProvider) DeepCopy() *AuthenticationProvider {
	if in == nil {
		return nil
	}
	out := new(AuthenticationProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPFieldNames) DeepCopyInto(out *LDAPFieldNames) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPFieldNames.
func (in *LDAPFieldNames) DeepCopy() *LDAPFieldNames {
	if in == nil {
		return nil
	}
	out := new(LDAPFieldNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPProvider) DeepCopyInto(out *LDAPProvider) {
	*out = *in
	if in.BindCredentials != nil {
		in, out := &in.BindCredentials, &out.BindCredentials
		*out = new(commonsv1alpha1.Credentials)
		(*in).DeepCopyInto(*out)
	}
	if in.LDAPFieldNames != nil {
		in, out := &in.LDAPFieldNames, &out.LDAPFieldNames
		*out = new(LDAPFieldNames)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(LDAPTLS)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPProvider.
func (in *LDAPProvider) DeepCopy() *LDAPProvider {
	if in == nil {
		return nil
	}
	out := new(LDAPProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPTLS) DeepCopyInto(out *LDAPTLS) {
	*out = *in
	if in.Verification != nil {
		in, out := &in.Verification, &out.Verification
		*out = new(commonsv1alpha1.TLSVerificationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPTLS.
func (in *LDAPTLS) DeepCopy() *LDAPTLS {
	if in == nil {
		return nil
	}
	out := new(LDAPTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCProvider) DeepCopyInto(out *OIDCProvider) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(OIDCTls)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCProvider.
func (in *OIDCProvider) DeepCopy() *OIDCProvider {
	if in == nil {
		return nil
	}
	out := new(OIDCProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCTls) DeepCopyInto(out *OIDCTls) {
	*out = *in
	if in.Verification != nil {
		in, out := &in.Verification, &out.Verification
		*out = new(commonsv1alpha1.TLSVerificationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCTls.
func (in *OIDCTls) DeepCopy() *OIDCTls {
	if in == nil {
		return nil
	}
	out := new(OIDCTls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticCredentialsSecret) DeepCopyInto(out *StaticCredentialsSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticCredentialsSecret.
func (in *StaticCredentialsSecret) DeepCopy() *StaticCredentialsSecret {
	if in == nil {
		return nil
	}
	out := new(StaticCredentialsSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticProvider) DeepCopyInto(out *StaticProvider) {
	*out = *in
	if in.CredentialsSecret != nil {
		in, out := &in.CredentialsSecret, &out.CredentialsSecret
		*out = new(StaticCredentialsSecret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticProvider.
func (in *StaticProvider) DeepCopy() *StaticProvider {
	if in == nil {
		return nil
	}
	out := new(StaticProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSPrivider) DeepCopyInto(out *TLSPrivider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSPrivider.
func (in *TLSPrivider) DeepCopy() *TLSPrivider {
	if in == nil {
		return nil
	}
	out := new(TLSPrivider)
	in.DeepCopyInto(out)
	return out
}
