//go:build !ignore_autogenerated

/*
Copyright 2025 ZNCDataDev.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	commonsv1alpha1 "github.com/zncdatadev/operator-go/pkg/apis/commons/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfigSpec) DeepCopyInto(out *ClusterConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfigSpec.
func (in *ClusterConfigSpec) DeepCopy() *ClusterConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoCluster) DeepCopyInto(out *DemoCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoCluster.
func (in *DemoCluster) DeepCopy() *DemoCluster {
	if in == nil {
		return nil
	}
	out := new(DemoCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoClusterList) DeepCopyInto(out *DemoClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DemoCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoClusterList.
func (in *DemoClusterList) DeepCopy() *DemoClusterList {
	if in == nil {
		return nil
	}
	out := new(DemoClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DemoClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoClusterSpec) DeepCopyInto(out *DemoClusterSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSpec)
		**out = **in
	}
	if in.ClusterConfig != nil {
		in, out := &in.ClusterConfig, &out.ClusterConfig
		*out = new(ClusterConfigSpec)
		**out = **in
	}
	if in.ClusterOperation != nil {
		in, out := &in.ClusterOperation, &out.ClusterOperation
		*out = new(commonsv1alpha1.ClusterOperationSpec)
		**out = **in
	}
	if in.Coordinator != nil {
		in, out := &in.Coordinator, &out.Coordinator
		*out = new(TrinoCoordinatorSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Worker != nil {
		in, out := &in.Worker, &out.Worker
		*out = new(TrinoWorkerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoClusterSpec.
func (in *DemoClusterSpec) DeepCopy() *DemoClusterSpec {
	if in == nil {
		return nil
	}
	out := new(DemoClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DemoClusterStatus) DeepCopyInto(out *DemoClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DemoClusterStatus.
func (in *DemoClusterStatus) DeepCopy() *DemoClusterStatus {
	if in == nil {
		return nil
	}
	out := new(DemoClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSpec) DeepCopyInto(out *ImageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSpec.
func (in *ImageSpec) DeepCopy() *ImageSpec {
	if in == nil {
		return nil
	}
	out := new(ImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrinoConfigSpec) DeepCopyInto(out *TrinoConfigSpec) {
	*out = *in
	in.RoleGroupConfigSpec.DeepCopyInto(&out.RoleGroupConfigSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrinoConfigSpec.
func (in *TrinoConfigSpec) DeepCopy() *TrinoConfigSpec {
	if in == nil {
		return nil
	}
	out := new(TrinoConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrinoCoordinatorSpec) DeepCopyInto(out *TrinoCoordinatorSpec) {
	*out = *in
	if in.RoleGroups != nil {
		in, out := &in.RoleGroups, &out.RoleGroups
		*out = make(map[string]TrinoRoleGroupSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(TrinoConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleConfig != nil {
		in, out := &in.RoleConfig, &out.RoleConfig
		*out = new(commonsv1alpha1.RoleConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OverridesSpec != nil {
		in, out := &in.OverridesSpec, &out.OverridesSpec
		*out = new(commonsv1alpha1.OverridesSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrinoCoordinatorSpec.
func (in *TrinoCoordinatorSpec) DeepCopy() *TrinoCoordinatorSpec {
	if in == nil {
		return nil
	}
	out := new(TrinoCoordinatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrinoRoleGroupSpec) DeepCopyInto(out *TrinoRoleGroupSpec) {
	*out = *in
	if in.OverridesSpec != nil {
		in, out := &in.OverridesSpec, &out.OverridesSpec
		*out = new(commonsv1alpha1.OverridesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(TrinoConfigSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrinoRoleGroupSpec.
func (in *TrinoRoleGroupSpec) DeepCopy() *TrinoRoleGroupSpec {
	if in == nil {
		return nil
	}
	out := new(TrinoRoleGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrinoWorkerSpec) DeepCopyInto(out *TrinoWorkerSpec) {
	*out = *in
	if in.RoleGroups != nil {
		in, out := &in.RoleGroups, &out.RoleGroups
		*out = make(map[string]TrinoRoleGroupSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(TrinoConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RoleConfig != nil {
		in, out := &in.RoleConfig, &out.RoleConfig
		*out = new(commonsv1alpha1.RoleConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OverridesSpec != nil {
		in, out := &in.OverridesSpec, &out.OverridesSpec
		*out = new(commonsv1alpha1.OverridesSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrinoWorkerSpec.
func (in *TrinoWorkerSpec) DeepCopy() *TrinoWorkerSpec {
	if in == nil {
		return nil
	}
	out := new(TrinoWorkerSpec)
	in.DeepCopyInto(out)
	return out
}
